export enum dateFormat {
    USA = 'MM/DD/YYYY',
    ISO = 'YYYY-MM-DD',
    GMT = 'ddd MMM DD YYYY HH:mm:ss [GMT]ZZ',
}

export enum dateTimeFormat {
    USA_LONG = 'MM/DD/YYYY hh:mm A',
    USA_SHORT = 'MM/DD/YYYY H:mm',
}
export const mockedData = {
    orderBatchId: 'ecf66c68-fed2-4967-b17b-e574fd269e94',
    result: {
        page: 1,
        size: 20,
        totalElements: 150,
        totalPages: 1,
        sort: 'UNSORTED',
        results: [
            {
                id: 1,
                store: {
                    id: 1,
                    name: 'HOME DEPOT STORE#100',
                    address: {
                        city: 'Loveland',
                        state: 'CO',
                    },
                    shipZone: {
                        id: 1,
                        code: 'C',
                        description: 'CENTRAL',
                    },
                    group: {
                        id: '1',
                        name: 'B',
                    },
                },
                product: {
                    id: 1,
                    code: {
                        id: 1,
                        code: '888-1234',
                    },
                    itemDescription: 'Perennial 2 Qt Assortment',
                    program: {
                        id: 1,
                        name: 'PERENNIALS',
                    },
                    category: {
                        id: 1,
                        name: 'PEREN2QT',
                        description: 'Perennial 2 Quart',
                    },
                    inventory: {
                        onHand: 13,
                        days: 0.0,
                    },
                },
                onOrder: {
                    qty: 0,
                    shelves: 0.0,
                    carts: 0.0,
                },
                availability: {
                    id: null,
                    qty: 0,
                    updatedQty: 0,
                    updatedShelves: 0.0,
                },
                predictedDemand: null,
                orderQuantity: [
                    {
                        id: null,
                        shipmentDate: '10/15/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/16/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/17/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/18/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/19/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                ],
            },
            {
                id: 2,
                store: {
                    id: 1,
                    name: 'HOME DEPOT STORE#100',
                    address: {
                        city: 'Loveland',
                        state: 'CO',
                    },
                    shipZone: {
                        id: 1,
                        code: 'C',
                        description: 'CENTRAL',
                    },
                    group: {
                        id: '1',
                        name: 'B',
                    },
                },
                product: {
                    id: 2,
                    code: {
                        id: 2,
                        code: '888-7633',
                    },
                    itemDescription: 'Assorted 2QT Aster',
                    program: {
                        id: 1,
                        name: 'PERENNIALS',
                    },
                    category: {
                        id: 1,
                        name: 'PEREN2QT',
                        description: 'Perennial 2 Quart',
                    },
                    inventory: {
                        onHand: 15,
                        days: 0.0,
                    },
                },
                onOrder: {
                    qty: 0,
                    shelves: 0.0,
                    carts: 0.0,
                },
                availability: {
                    id: 41,
                    qty: 507,
                    updatedQty: 0,
                    updatedShelves: 0.0,
                },
                predictedDemand: {
                    qty: 188,
                    shelves: 18.8,
                },
                orderQuantity: [
                    {
                        id: null,
                        shipmentDate: '10/15/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/16/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/17/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/18/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/19/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                ],
            },
            {
                id: 3,
                store: {
                    id: 1,
                    name: 'HOME DEPOT STORE#100',
                    address: {
                        city: 'Loveland',
                        state: 'CO',
                    },
                    shipZone: {
                        id: 1,
                        code: 'C',
                        description: 'CENTRAL',
                    },
                    group: {
                        id: '1',
                        name: 'B',
                    },
                },
                product: {
                    id: 3,
                    code: {
                        id: 3,
                        code: '888-8821',
                    },
                    itemDescription: 'Assorted 2Qt Coreopsis',
                    program: {
                        id: 1,
                        name: 'PERENNIALS',
                    },
                    category: {
                        id: 1,
                        name: 'PEREN2QT',
                        description: 'Perennial 2 Quart',
                    },
                    inventory: {
                        onHand: 12,
                        days: 0.0,
                    },
                },
                onOrder: {
                    qty: 0,
                    shelves: 0.0,
                    carts: 0.0,
                },
                availability: {
                    id: 40,
                    qty: 361,
                    updatedQty: 0,
                    updatedShelves: 0.0,
                },
                predictedDemand: {
                    qty: 248,
                    shelves: 24.8,
                },
                orderQuantity: [
                    {
                        id: null,
                        shipmentDate: '10/15/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/16/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/17/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/18/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/19/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                ],
            },
            {
                id: 4,
                store: {
                    id: 1,
                    name: 'HOME DEPOT STORE#100',
                    address: {
                        city: 'Loveland',
                        state: 'CO',
                    },
                    shipZone: {
                        id: 1,
                        code: 'C',
                        description: 'CENTRAL',
                    },
                    group: {
                        id: '1',
                        name: 'B',
                    },
                },
                product: {
                    id: 4,
                    code: {
                        id: 4,
                        code: '888-9833',
                    },
                    itemDescription: 'Assorted 2QT Astilbe',
                    program: {
                        id: 1,
                        name: 'PERENNIALS',
                    },
                    category: {
                        id: 1,
                        name: 'PEREN2QT',
                        description: 'Perennial 2 Quart',
                    },
                    inventory: {
                        onHand: 21,
                        days: 0.0,
                    },
                },
                onOrder: {
                    qty: 0,
                    shelves: 0.0,
                    carts: 0.0,
                },
                availability: {
                    id: 45,
                    qty: 1245,
                    updatedQty: 0,
                    updatedShelves: 0.0,
                },
                predictedDemand: {
                    qty: 473,
                    shelves: 47.3,
                },
                orderQuantity: [
                    {
                        id: null,
                        shipmentDate: '10/15/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/16/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/17/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/18/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/19/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                ],
            },
            {
                id: 5,
                store: {
                    id: 1,
                    name: 'HOME DEPOT STORE#100',
                    address: {
                        city: 'Loveland',
                        state: 'CO',
                    },
                    shipZone: {
                        id: 1,
                        code: 'C',
                        description: 'CENTRAL',
                    },
                    group: {
                        id: '1',
                        name: 'B',
                    },
                },
                product: {
                    id: 5,
                    code: {
                        id: 5,
                        code: '888-3421',
                    },
                    itemDescription: 'Assorted 2QT Peony',
                    program: {
                        id: 1,
                        name: 'PERENNIALS',
                    },
                    category: {
                        id: 1,
                        name: 'PEREN2QT',
                        description: 'Perennial 2 Quart',
                    },
                    inventory: {
                        onHand: 8,
                        days: 0.0,
                    },
                },
                onOrder: {
                    qty: 0,
                    shelves: 0.0,
                    carts: 0.0,
                },
                availability: {
                    id: 36,
                    qty: 1349,
                    updatedQty: 0,
                    updatedShelves: 0.0,
                },
                predictedDemand: {
                    qty: 601,
                    shelves: 60.1,
                },
                orderQuantity: [
                    {
                        id: null,
                        shipmentDate: '10/15/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/16/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/17/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/18/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/19/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                ],
            },
            {
                id: 6,
                store: {
                    id: 1,
                    name: 'HOME DEPOT STORE#100',
                    address: {
                        city: 'Loveland',
                        state: 'CO',
                    },
                    shipZone: {
                        id: 1,
                        code: 'C',
                        description: 'CENTRAL',
                    },
                    group: {
                        id: '1',
                        name: 'B',
                    },
                },
                product: {
                    id: 6,
                    code: {
                        id: 6,
                        code: '888-5533',
                    },
                    itemDescription: 'Assorted 2QT Echinacea',
                    program: {
                        id: 1,
                        name: 'PERENNIALS',
                    },
                    category: {
                        id: 1,
                        name: 'PEREN2QT',
                        description: 'Perennial 2 Quart',
                    },
                    inventory: {
                        onHand: 11,
                        days: 0.0,
                    },
                },
                onOrder: {
                    qty: 0,
                    shelves: 0.0,
                    carts: 0.0,
                },
                availability: {
                    id: 38,
                    qty: 427,
                    updatedQty: 0,
                    updatedShelves: 0.0,
                },
                predictedDemand: {
                    qty: 248,
                    shelves: 24.8,
                },
                orderQuantity: [
                    {
                        id: null,
                        shipmentDate: '10/15/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/16/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/17/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/18/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/19/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                ],
            },
            {
                id: 7,
                store: {
                    id: 1,
                    name: 'HOME DEPOT STORE#100',
                    address: {
                        city: 'Loveland',
                        state: 'CO',
                    },
                    shipZone: {
                        id: 1,
                        code: 'C',
                        description: 'CENTRAL',
                    },
                    group: {
                        id: '1',
                        name: 'B',
                    },
                },
                product: {
                    id: 7,
                    code: {
                        id: 7,
                        code: '888-7723',
                    },
                    itemDescription: 'Assorted 2QT Scabiosa',
                    program: {
                        id: 1,
                        name: 'PERENNIALS',
                    },
                    category: {
                        id: 1,
                        name: 'PEREN2QT',
                        description: 'Perennial 2 Quart',
                    },
                    inventory: {
                        onHand: 19,
                        days: 0.0,
                    },
                },
                onOrder: {
                    qty: 0,
                    shelves: 0.0,
                    carts: 0.0,
                },
                availability: {
                    id: 33,
                    qty: 204,
                    updatedQty: 0,
                    updatedShelves: 0.0,
                },
                predictedDemand: {
                    qty: 128,
                    shelves: 12.8,
                },
                orderQuantity: [
                    {
                        id: null,
                        shipmentDate: '10/15/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/16/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/17/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/18/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/19/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                ],
            },
            {
                id: 8,
                store: {
                    id: 1,
                    name: 'HOME DEPOT STORE#100',
                    address: {
                        city: 'Loveland',
                        state: 'CO',
                    },
                    shipZone: {
                        id: 1,
                        code: 'C',
                        description: 'CENTRAL',
                    },
                    group: {
                        id: '1',
                        name: 'B',
                    },
                },
                product: {
                    id: 8,
                    code: {
                        id: 8,
                        code: '888-4433',
                    },
                    itemDescription: 'Assorted 2QT Rudbeckia',
                    program: {
                        id: 1,
                        name: 'PERENNIALS',
                    },
                    category: {
                        id: 1,
                        name: 'PEREN2QT',
                        description: 'Perennial 2 Quart',
                    },
                    inventory: {
                        onHand: 9,
                        days: 0.0,
                    },
                },
                onOrder: {
                    qty: 0,
                    shelves: 0.0,
                    carts: 0.0,
                },
                availability: {
                    id: 39,
                    qty: 611,
                    updatedQty: 0,
                    updatedShelves: 0.0,
                },
                predictedDemand: {
                    qty: 248,
                    shelves: 24.8,
                },
                orderQuantity: [
                    {
                        id: null,
                        shipmentDate: '10/15/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/16/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/17/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/18/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/19/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                ],
            },
            {
                id: 9,
                store: {
                    id: 4,
                    name: 'HOME DEPOT STORE#200',
                    address: {
                        city: 'Green Bay',
                        state: 'WI',
                    },
                    shipZone: {
                        id: 1,
                        code: 'C',
                        description: 'CENTRAL',
                    },
                    group: {
                        id: '2',
                        name: 'A',
                    },
                },
                product: {
                    id: 1,
                    code: {
                        id: 1,
                        code: '888-1234',
                    },
                    itemDescription: 'Perennial 2 Qt Assortment',
                    program: {
                        id: 1,
                        name: 'PERENNIALS',
                    },
                    category: {
                        id: 1,
                        name: 'PEREN2QT',
                        description: 'Perennial 2 Quart',
                    },
                    inventory: {
                        onHand: 17,
                        days: 0.0,
                    },
                },
                onOrder: {
                    qty: 0,
                    shelves: 0.0,
                    carts: 0.0,
                },
                availability: {
                    id: null,
                    qty: 0,
                    updatedQty: 0,
                    updatedShelves: 0.0,
                },
                predictedDemand: null,
                orderQuantity: [
                    {
                        id: null,
                        shipmentDate: '10/15/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/16/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/17/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/18/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/19/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                ],
            },
            {
                id: 10,
                store: {
                    id: 4,
                    name: 'HOME DEPOT STORE#200',
                    address: {
                        city: 'Green Bay',
                        state: 'WI',
                    },
                    shipZone: {
                        id: 1,
                        code: 'C',
                        description: 'CENTRAL',
                    },
                    group: {
                        id: '2',
                        name: 'A',
                    },
                },
                product: {
                    id: 2,
                    code: {
                        id: 2,
                        code: '888-7633',
                    },
                    itemDescription: 'Assorted 2QT Aster',
                    program: {
                        id: 1,
                        name: 'PERENNIALS',
                    },
                    category: {
                        id: 1,
                        name: 'PEREN2QT',
                        description: 'Perennial 2 Quart',
                    },
                    inventory: {
                        onHand: 19,
                        days: 0.0,
                    },
                },
                onOrder: {
                    qty: 0,
                    shelves: 0.0,
                    carts: 0.0,
                },
                availability: {
                    id: 41,
                    qty: 507,
                    updatedQty: 0,
                    updatedShelves: 0.0,
                },
                predictedDemand: {
                    qty: 248,
                    shelves: 24.8,
                },
                orderQuantity: [
                    {
                        id: null,
                        shipmentDate: '10/15/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/16/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/17/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/18/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/19/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                ],
            },
            {
                id: 11,
                store: {
                    id: 4,
                    name: 'HOME DEPOT STORE#200',
                    address: {
                        city: 'Green Bay',
                        state: 'WI',
                    },
                    shipZone: {
                        id: 1,
                        code: 'C',
                        description: 'CENTRAL',
                    },
                    group: {
                        id: '2',
                        name: 'A',
                    },
                },
                product: {
                    id: 3,
                    code: {
                        id: 3,
                        code: '888-8821',
                    },
                    itemDescription: 'Assorted 2Qt Coreopsis',
                    program: {
                        id: 1,
                        name: 'PERENNIALS',
                    },
                    category: {
                        id: 1,
                        name: 'PEREN2QT',
                        description: 'Perennial 2 Quart',
                    },
                    inventory: {
                        onHand: 5,
                        days: 0.0,
                    },
                },
                onOrder: {
                    qty: 0,
                    shelves: 0.0,
                    carts: 0.0,
                },
                availability: {
                    id: 40,
                    qty: 361,
                    updatedQty: 0,
                    updatedShelves: 0.0,
                },
                predictedDemand: {
                    qty: 308,
                    shelves: 30.8,
                },
                orderQuantity: [
                    {
                        id: null,
                        shipmentDate: '10/15/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/16/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/17/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/18/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                    {
                        id: null,
                        shipmentDate: '10/19/2025',
                        qty: 0,
                        shelves: 0.0,
                        carts: 0.0,
                        exportedOrderQty: null,
                        forecast: null,
                    },
                ],
            },
        ],
    },
};

export enum defaultRowFields {
    ID = 'id',
    STORE = 'store',
    CITY = 'city',
    STATE = 'state',
    SHIP_ZONE_DESCRIPTION = 'ship_zone_description',
    SHIP_ZONE_CODE = 'ship_zone_code',
    SHIP_ZONE_ID = 'ship_zone_id',
    STORE_GROUP_NAME = 'store_group_name',
    STORE_GROUP_ID = 'store_group_id',
    PRODUCT_PROGRAM_NAME = 'product_program_name',
    PRODUCT_PROGRAM_ID = 'product_program_id',
    PRODUCT_CATEGORY_NAME = 'product_category_name',
    PRODUCT_CATEGORY_ID = 'product_category_id',
    PRODUCT_CATEGORY_DESCRIPTION = 'product_category_description',
    PRODUCT_CODE = 'product_code',
    PRODUCT_ID = 'product_id',
    PREDICTED_DEMAND = 'predicted_demand',
    ITEM_DESCRIPTION = 'item_description',
    STORE_INVENTORY_ON_HAND = 'store_inventory_on_hand',
    STORE_INVENTORY_DAYS = 'store_inventory_days',
    DEMAND_QTY = 'demand_qty',
    DEMAND_SHELVES = 'demand_shelves',
    ON_ORDER = 'on_order',
    AVAILABILITY_ID = 'availability_id',
    AVAILABILITY_QTY = 'availability_qty',
    AVAILABILITY_UPDATED_QTY = 'availability_updated_qty',
    AVAILABILITY_UPDATED_SHELVES = 'availability_updated_shelves',
}

export const defaultColumns = [
    {field: defaultRowFields.ID, headerName: 'ID', sortable: false, width: 50, headerClass: 'outer-header'},
    {field: defaultRowFields.STORE, headerName: 'Store', sortable: true, width: 160, headerClass: 'outer-header'},
    {field: defaultRowFields.CITY, headerName: 'City', sortable: true, width: 100, headerClass: 'outer-header'},
    {field: defaultRowFields.STATE, headerName: 'State', sortable: true, width: 65, headerClass: 'outer-header'},
    {
        field: defaultRowFields.SHIP_ZONE_DESCRIPTION,
        headerName: 'Ship Zone',
        sortable: true,
        width: 100,
        headerClass: 'outer-header',
    },
    {
        field: defaultRowFields.STORE_GROUP_NAME,
        headerName: 'Store Group',
        sortable: true,
        width: 70,
        headerClass: 'outer-header',
    },
    {
        field: defaultRowFields.PRODUCT_PROGRAM_NAME,
        headerName: 'Program',
        sortable: true,
        width: 100,
        headerClass: 'outer-header',
    },
    {
        field: defaultRowFields.PRODUCT_CATEGORY_NAME,
        headerName: 'Category',
        sortable: true,
        width: 100,
        headerClass: 'outer-header',
    },
    {
        field: defaultRowFields.PRODUCT_CODE,
        headerName: 'Product Code',
        sortable: true,
        width: 80,
        headerClass: 'outer-header',
    },
    {
        field: defaultRowFields.ITEM_DESCRIPTION,
        headerName: 'Item Description',
        sortable: true,
        width: 140,
        headerClass: 'outer-header',
    },
    {
        headerName: 'Store Inventory',
        headerClass: 'outer-header',
        children: [
            {
                field: defaultRowFields.STORE_INVENTORY_ON_HAND,
                headerName: 'On Hand',
                sortable: true,
                width: 60,
                headerClass: 'nested-header',
            },
            {
                field: defaultRowFields.STORE_INVENTORY_DAYS,
                headerName: 'Days',
                sortable: true,
                width: 60,
                headerClass: 'nested-header',
            },
        ],
    },
    {
        headerName: 'Demand',
        headerClass: 'outer-header',
        children: [
            {
                field: defaultRowFields.DEMAND_QTY,
                headerName: 'Qty',
                sortable: true,
                width: 70,
                headerClass: 'nested-header',
            },
            {
                field: defaultRowFields.DEMAND_SHELVES,
                headerName: 'Shelves',
                sortable: true,
                width: 70,
                headerClass: 'nested-header',
            },
        ],
    },
    {
        field: defaultRowFields.ON_ORDER,
        headerClass: 'outer-header',
        headerName: 'On Order',
        sortable: true,
        width: 60,
        wrapText: true,
        autoHeight: true,
    },
    {
        headerName: 'Availability',
        headerClass: 'outer-header',
        children: [
            {
                field: defaultRowFields.AVAILABILITY_QTY,
                headerName: 'Qty',
                sortable: true,
                width: 70,
                headerClass: 'nested-header',
            },
            {
                field: defaultRowFields.AVAILABILITY_UPDATED_QTY,
                headerName: 'Updated Qty',
                sortable: true,
                width: 70,
                headerClass: 'nested-header',
            },
            {
                field: defaultRowFields.AVAILABILITY_UPDATED_SHELVES,
                headerName: 'Updated Shelves',
                sortable: true,
                width: 70,
                headerClass: 'nested-header',
            },
        ],
    },
];
